[package]
name = "syntect-tui"
version = "2.0.0"
edition = "2021"
license = "MIT"
description = "A lightweight translation layer between syntect.rs and tui.rs style types"
authors = ["Pierre Chanquion <{FORENAME}.{FIRST_FIVE_LETTERS_OF_SURNAME}.io>", "Mick Harrigan <mharrigan328@gmail.com>"]

[dependencies]
custom_error = "1.9.2"
ratatui = "0.25.0"
syntect = "5.0.0"

[dev-dependencies]
rstest = "0.18.2"
